<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>MediVault.KeyGen</RootNamespace>
    <AssemblyName>MediVault.KeyGen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediVault.Licensing\MediVault.Licensing.csproj" />
  </ItemGroup>

</Project>
