<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MediVault.Licensing</RootNamespace>
    <AssemblyName>MediVault.Licensing</AssemblyName>
  </PropertyGroup>

</Project>
